### ISSUE TITLE
Is setting apt-mirrors for ubuntu required to run this role?

### ISSUE THREAD

**Issue by berkes** [cimnine/ansible-jitsi-meet-role#1]
I might misunderstand something, so please correct me if I'm wrong.

The task configures an apt-mirror for ubuntu. This is quite nonstandard and breaks my own setup, where I have a "base" role that configures apt on all systems according to our guidelines and setups. 
One of that is to set the mirrors.

So, it seems to a bot out of place in this role. AFAIK the role works fine without setting mirrors on Ubuntu, but I did not test that.

If so, should this step not be removed instead? And if so, please let me know and I'll mock up a PR for that.

**Comment by cimnine** [comment]
Jitsi needs access to Ubuntu's _universe_ repository. Maybe there's a better way to solve this. But that's the reason it's in the role.

**Comment by berkes** [comment]
I now understand the reasoning better. My VPS has that enabled by default, so in my case it was a bit redundant, but not breaking stuff either.

Guess that closes this issue.
