### ISSUE TITLE
server_names_hash_bucket_size 64; is set globally and conflicts with other config.

### ISSUE THREAD

**Issue by berkes** [cimnine/ansible-jitsi-meet-role#2]
The vhost should probably not set it globally.

Either this should be a setting in `/etc/nginx/nginx.conf` or it should be moved into the vhost (if possible at all?).

**Comment by cimnine** [comment]
It's possible to set individualy. See http://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_bucket_size.

**Comment by berkes** [comment]
I'm not sure if I understand you correctly. https://github.com/cimnine/ansible-jitsi-meet-role/blob/master/templates/nginx-vhost.conf.j2#L3 sets it globally. 

nginx docs say that the `Context: 	http` is required. So afaik it can be only set globally.

**Comment by cimnine** [comment]
It can only be set globally so it is set globally. We're on the same page on this. Now I may need another hint on what your concern is.

**Comment by berkes** [comment]
My concern is that a *role* is setting a global nginx configuration. 

That means that this role:
* assumes you don't configure nginx yourself.
* forces you to follow its hardcoded env for your entire nginx conf.

In my case the role errored (and brought the server down) because I embedded the role in our generic playbook-setup that:

* does loads of stuff like firewalls, memory, bootstrapping etc. 
* but *also* our generic nginx-best practices. Like setting `server_names_hash_bucket_size`.

IMO - but we might not agree on that- a role should stay away from global settings.

# Possible Solutions:

* Document this behaviour. IMO documenting issues is a poor mans "solution" to actually solving the issue though.
* Leave it to the implementor to set things like `server_names_hash_bucket_size`. This might cause the role to start a non-functioning jitsi though: I'm not sure if the default in ubuntu 18:04 breaks jitsi, but AFAIK it will work with the default setting: the global here seems "merely" an improvement; I did not test this though.
* Set it in the global nginx.conf instead with e.g. a `lineinfile`. The global nginx conf is the place to set global settings, not vhosts. (we have several vhosts on this server for jitsi-related tools).

**Comment by cimnine** [comment]
Thank you for the clarifications. I did not understand that it was important in your case that global options are defined in the central `nginx.conf` file. Could you have a look at #3? Would this serve your purpose?

**Comment by berkes** [comment]
#3 indeed fixes this issue perfectly! 

Any conflict can now be resolved there in a more robust way, if needed.

Thanks a million!
